shallow_clone: true

os:
  - Visual Studio 2015

environment:
  matrix:
  - TOOLSET: vs2013
  - TOOLSET: vs2015

configuration:
  - Debug
  - Release

install:
  - git clone --depth 1 https://github.com/bkaradzic/bx ..\bx
  - git clone --depth 1 https://github.com/bkaradzic/bimg ..\bimg
  - ..\bx\tools\bin\windows\genie --with-tools %TOOLSET%

build:
  project: .build/projects/$(TOOLSET)/bgfx.sln
